### ISSUE TITLE
neovim async support

### ISSUE THREAD

**Issue by campbellr** [torbiak/rut.vim#1]
It would be great if rut could take advantage of the async plugin support in neovim so that running tests doesn't block the editor. This would be especially helpful when running `RutRunAll`.

It might also make it less painful to automatically run the tests on save.

It might be worth looking at [neomake](https://github.com/benekastah/neomake), although i was having some issues getting it to work...

**Comment by torbiak** [comment]
Yeah, neomake wasn't working for me either and it didn't seem like much work to reimplement what I needed, so I did.

Multiline errorformats make things messy, since they don't match output they should if it's added line-by-line with caddexpr. I could parse the accumulated output for errorformat matches every time (or every few times) output is received, but it seems wasteful---I'm not sure if it's actually significant---and wouldn't be very helpful in what I expect to be the typical case, where the test runner outputs a bunch of dots and F's on the same line and doesn't print any information about the failures until all the tests have run. It would be more useful if you wrote an alternate runner that printed the error location as soon as the test failed, but in that case you'd print the errors linewise unless you were into pain and writing errorformat patterns and and wouldn't need a multiline errorformat, anyway.

**Comment by campbellr** [comment]
Awesome, can't wait to try it!
